# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#   parameter_name: value
    class.guzzle.response: Guzzle\Http\Message\Response
    class.guzzle.client: Guzzle\Http\Client
    git.baseurl: https://api.github.com

services:
#   service_name:
#       class: AppBundle\Directory\ClassName
#       arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.git.user:
        class: AppBundle\Git\GitUser
    app.git.repository:
        class: AppBundle\Git\GitRepository
    guzzle.git.client:
        class: %class.guzzle.client%
        arguments: [%git.baseurl%]